########################################################################################
# INPUT
########################################################################################

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}


########################################################################################
# GENERAL
# Layout and Border settings
########################################################################################

general {
    # Gaps and Borders
    gaps_in = 6
    gaps_out = 10
    border_size = 2

    # Colors (Referencing variables defined at the top)
    col.active_border = $primary $secondary 45deg
    col.inactive_border = $inactive

    # Layout
    layout = dwindle
    
    # Tearing
    allow_tearing = false
}


########################################################################################
#: DECORATION
# Visual effects like Blur and Shadows
########################################################################################

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.9

    # Blur settings
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }
}


########################################################################################
# LAYOUTS
########################################################################################

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
    pseudotile = false
    preserve_split = yes 
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout
}


########################################################################################
# MISC
########################################################################################

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 0
}
